Tokenize
oldmud0/codeu17-group18 pull request #12
Opened 2017-06-12 08:42 UTC by aishwmano

Added working tokenize functionality

2017-06-12 12:08 UTC, cbick commented on src/codeu/chat/util/Tokenizer.java
> +public final class Tokenizer {
the class and its public methods could use some documentation

2017-06-12 12:08 UTC, cbick commented on src/codeu/chat/util/Tokenizer.java
> +  private StringBuilder token;
token and source should be final, i think

2017-06-12 12:08 UTC, cbick commented on test/codeu/chat/util/TokenizerTest.java
> +}
test imbalanced quotes, mixture of quoted/nonquoted?

2017-06-13 01:04 UTC, oldmud0 commented on test/codeu/chat/util/TokenizerTest.java
> +}
Don't forget Unicode.

2017-06-13 23:53 UTC, oldmud0 requested changes
This big red 'X' looks very imposing, but I just need you to address those changes before I merge everything, as the deadline is approaching rather quickly.

2017-06-13 23:53 UTC, oldmud0 commented on src/codeu/chat/client/commandline/Chat.java
> +import java.util.*;
Don't do wildcard imports; they cause confusion in many cases. Let Eclipse take care of imports for you.

2017-06-13 23:53 UTC, oldmud0 commented on src/codeu/chat/client/commandline/Chat.java
> +    args.remove(0);
[`List.remove`](http://docs.oracle.com/javase/8/docs/api/java/util/List.html#remove-int-) also returns the element at that position before it was removed, so you can condense these two lines into one:
```java
final String command = args.remove(0);
```

(edit: looks like you already know this, as shown by later code, so I'm left scratching my head as to why this is here.)

2017-06-13 23:53 UTC, oldmud0 commented on src/codeu/chat/util/Tokenizer.java
> +import java.lang.*;
Remove wildcard imports.

2017-06-13 23:53 UTC, oldmud0 commented on src/codeu/chat/util/Tokenizer.java
> +public final class Tokenizer {
I second this.

2017-06-13 23:53 UTC, oldmud0 commented on src/codeu/chat/util/Tokenizer.java
> +  private StringBuilder token;
Indeed.

2017-06-14 05:13 UTC, merged

2017-06-14 05:59 UTC, aishwmano commented
Made the suggested changes.