Version info
oldmud0/codeu17-group18 pull request #7
Opened 2017-05-21 04:48 UTC by oldmud0

Addresses #1. Tutorial was a little old and conflicts with the next tutorial (uptime, which is #2), so I purposely strayed from the tutorial's suggested class name `ServerInfo` and called it `VersionInfo` instead.

2017-05-22 14:34 UTC, oldmud0 reviewed
Self-review

2017-05-22 14:34 UTC, oldmud0 commented on src/codeu/chat/server/View.java
> +
This extra whitespace was not necessary.

2017-05-22 14:34 UTC, oldmud0 commented on src/codeu/chat/common/VersionInfo.java
> +      this.version = null;
Not sure whether to assign to `Uuid.NULL` or `null`, as assigning to `Uuid.NULL` somewhat complicates validation (see `codeu.chat.client.commandline.Chat` line 195 where `version` is checked for `null`).

2017-05-22 14:34 UTC, oldmud0 commented on src/codeu/chat/client/commandline/Chat.java
>          System.out.println("    Exit the program.");
I consider this part of the code to be a little ugly, as you could use annotations or even just a description field on a `Panel.Command` and then enumerate each possible command in the order you want.

2017-05-22 14:34 UTC, oldmud0 commented on src/codeu/chat/client/commandline/Chat.java
> +          if (version == null) {
`|| version.equals(Uuid.NULL)`?

2017-05-23 14:02 UTC, oldmud0 commented
I need to add a unit test.

2017-06-01 17:47 UTC, cbick requested changes

2017-06-01 17:47 UTC, cbick commented on src/codeu/chat/client/commandline/Chat.java
>          System.out.println("    Exit the program.");
agreed... an enum would probably be the right construct here. (but no need to make that change).

2017-06-01 17:47 UTC, cbick commented on src/codeu/chat/client/commandline/Chat.java
> +          if (version == null) {
sounds reasonable, depending on what the docs for getVersion() say (hint hint)

2017-06-01 17:47 UTC, cbick commented on src/codeu/chat/common/BasicView.java
> +  //   Return the server's version.
it's usually nice to explain that it can return null in case of an error (although i see that the other method docs aren't nice like that)

2017-06-01 17:47 UTC, cbick commented on src/codeu/chat/common/VersionInfo.java
> + * For clients, this can be used to determine whether or not the server version
`* <p>For clients, ...`

(since you're using javadoc)

2017-06-01 17:47 UTC, cbick commented on src/codeu/chat/common/VersionInfo.java
> +  private Uuid version;
this should be final

2017-06-01 17:47 UTC, cbick commented on src/codeu/chat/common/VersionInfo.java
> +      this.version = null;
if CURRENT_VERSION was a Uuid instead of a string you could avoid this quandary

2017-06-01 17:47 UTC, cbick commented on src/codeu/chat/server/Server.java
> +        Uuid.SERIALIZER.write(out, version.getVersion());
have you tested that this works when getVersion() returns null?

2017-06-01 19:39 UTC, oldmud0 commented on src/codeu/chat/common/VersionInfo.java
> + * For clients, this can be used to determine whether or not the server version
Ah, I thought it would make a new paragraph from the extra blank line.

2017-06-01 20:18 UTC, oldmud0 commented on src/codeu/chat/common/VersionInfo.java
> +  private Uuid version;
It can't be final with the current code because the compiler counts the assignment in the catch statement as a reassignment.

2017-06-01 20:27 UTC, oldmud0 commented on src/codeu/chat/common/VersionInfo.java
> +      this.version = null;
Are you saying to invoke `Uuid.parse("1.0.0")` instead? The compiler will expect me to catch the IOException, but not possible inline. I could try making a `private static final Uuid getCurrentVersionUuid()` and then pass that to the default constructor.

2017-06-07 00:11 UTC, oldmud0 commented
It does not appear to be possible to add a unit test for VersionInfo yet, as there is no unit test skeleton even laid out for the server or client.

2017-06-13 04:40 UTC, oldmud0 commented
I took a U-turn with the whole `return null` thing, as it is quite the code smell, especially when a more specific null is available: `Uuid.NULL`, which is more parser-friendly than simply `null`. So, don't return just null, return `Uuid.NULL`. The parser is happy, Java is happy, Colin is happy, and the other devs are, too.

2017-06-14 18:56 UTC, merged