Version info
oldmud0/codeu17-group18 pull request #8
Opened 2017-05-21 23:06 UTC by annyue

Basically followed the tutorial. It shows a ton spacing changes because I auto indented using Eclipse.

2017-05-22 14:20 UTC, oldmud0 commented
I see you're having problems with the formatting. [Here](https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml) is an XML of the official Google formatting style.

To import it into Eclipse, click on **your project name > Properties > Java > Code Style > Formatter > Configure Project Specific Settings...** (I believe it should already be set to project-specific, but if you see this link on the top right of the window, click it) **> Import...**

Then when you're done importing, go to the drop-down and select GoogleStyle as the active profile. Click OK, and then **right click blocks of your code > Source > Format (Ctrl+Shift+F)**. The indentation will change to 2 spaces per tab, whitespace in empty lines will be removed, and such.

2017-06-01 17:39 UTC, cbick requested changes

2017-06-01 17:39 UTC, cbick commented on src/codeu/chat/client/core/View.java
> +    try (final Connection connection = this.source.connect()) {
just "source.connect()". It's usually fine to leave 'this' implied except in cases of variable shadowing, and it's consistent with the rest of this class.

2017-06-01 17:39 UTC, cbick commented on src/codeu/chat/common/BasicView.java
> +  // Return server info
it's usually nice to explain that it can return null in case of an error (although i see that the other method docs aren't nice like that)

2017-06-01 17:39 UTC, cbick commented on src/codeu/chat/common/ServerInfo.java
> +  private final static String SERVER_VERSION = "1.0.0";
could we make this a Uuid instead of a String and that way avoid the error check in the constructor?

2017-06-01 17:39 UTC, cbick commented on src/codeu/chat/server/Server.java
> +  private static final ServerInfo info = new ServerInfo();
static final constants should be named in all upper case (so 'INFO' instead of 'info')

2017-06-01 17:39 UTC, cbick commented on src/codeu/chat/server/Server.java
> +        Uuid.SERIALIZER.write(out, info.getVersion());
have you tested what happens when this writes null? (since it looks like .getVersion() can return null sometimes)

2017-06-04 00:03 UTC, annyue commented on src/codeu/chat/client/core/View.java
> +    try (final Connection connection = this.source.connect()) {
done

2017-06-08 00:39 UTC, annyue commented on src/codeu/chat/common/ServerInfo.java
> +  private final static String SERVER_VERSION = "1.0.0";
done

2017-06-26 19:31 UTC, closed without merging